apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: devops-lab
type: Opaque
# Los valores deben estar en base64
# echo -n "postgres" | base64  → cG9zdGdyZXM=
# echo -n "1234"     | base64  → MTIzNA==
# echo -n "registro_gastos" | base64 → cmVnaXN0cm9fZ2FzdG9z
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzNA==
  POSTGRES_DB: cmVnaXN0cm9fZ2FzdG9z